project:
  type: book
  output-dir: docs

book:
  title: "SQL for Data Analysis using R"
  author: "Ian Gow"
  date: today
  date-format: "D MMMM YYYY"
  
  chapters:
    - index.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
