project:
  type: book
  output-dir: docs
  
book:
  title: "SQL for Data Analysis using R"
  author: "Ian Gow"
  date: today
  date-format: "D MMMM YYYY"
  
  chapters:
    - index.qmd
    - sql-intro.qmd
    - dbplyr-intro.qmd
    - time-series.qmd
    - cohorts.qmd
    - text.qmd
    - anomalies.qmd
    - experiments.qmd
    - complex-data.qmd
    - conclusion.qmd
    - appendix.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-after-body: statcounter.html